added freesurfer license to container

diff --git a/main b/main
--- a/main
+++ b/main
@@ -4,15 +4,15 @@ module load singularity 2> /dev/null
 
 ## run file conversion shell
 #singularity exec -e docker://brainlife/freesurfer ./preprocess.sh
-./preprocess.sh
+time singularity exec -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./preprocess.sh"
 
 ## run main
-singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main
+time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main
 
 echo "Network Pipeline Complete"
 
 if [ ! -s pconn.mat ];
 then
-	echo "output missing"
-	exit 1
+    echo "output missing"
+    exit 1
 fi
